### ISSUE TITLE
Presentation Slides

### ISSUE THREAD

**Issue by mcne65** [petergoodin/ga_ds101#1]
Please let me know when you have them up

**Comment by petergoodin** [comment]
I will indeed. The formatting became corrupted when I tried to export them, so I'm now looking for a way to make them readable again. 

Peter

**Comment by petergoodin** [comment]
Hi Sirani, 

Uploaded now. Sorry for the delay.

**Comment by mcne65** [comment]
Can't see the file?

**Comment by mcne65** [comment]
Ah thank you - found it. 
Regards
Sirani McNeill
